[act]

% asserts.cc.bin

[assert]

stderr equals <<EOF
[----] asserts.cc:15: Assertion Failed
[----]   
[----]   assert is fatal, expect isn't
[----]   
[----] asserts.cc:16: Assertion Failed
[----]   
[----]   This assert runs
[----]   
[FAIL] asserts::base
[----] asserts.cc:167: Assertion Failed
[----]   throw(std::runtime_error, {}): 
[----]     message: <nothing was thrown>
[----] asserts.cc:169: Assertion Failed
[----]   throw(std::bad_alloc, throw std::invalid_argument("some other message")): 
[----]     message: "some other message"
[FAIL] asserts::exception
[----] asserts.cc:21: Assertion Failed
[----]   
[----]   You can fail an assertion with a message from anywhere
[----]   
[----] asserts.cc:22: Assertion Failed
[FAIL] asserts::old_school
[====] Synthesis: Tested: 9 | Passing: 6 | Failing: 3 | Crashing: 0 
EOF
